### Register a new user
POST http://localhost:5000/register
Content-Type: application/json

{
  "username": "user",
  "email": "user@gmail.com",
  "password": "user"
}



### Login
POST http://localhost:5000/login
Content-Type: application/json

{
  "username": "user",
  "password": "user"
}


### Profile
GET http://localhost:5000/profile
Content-Type: application/json


### Logout
POST http://localhost:5000/logout
Content-Type: application/json